apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-gallery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-gallery
  template:
    metadata:
      labels:
        app: s3-gallery
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: s3-gallery
          image: noakhali/reads3:10   
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: "us-east-2"
            - name: S3_BUCKET_NAME
              value: "shefat"

---
apiVersion: v1
kind: Service
metadata:
  name: s3-gallery-svc
  namespace: default
spec:
  selector:
    app: s3-gallery
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
